name: GitHub

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2

    - name: Close Finder windows not to obscure test screenshots
      run: |
        launchctl unload /System/Library/LaunchAgents/com.apple.Finder.plist
        defaults delete com.apple.Finder
        launchctl load /System/Library/LaunchAgents/com.apple.Finder.plist
        open /System/Library/CoreServices/Finder.app
    - name: All Tests
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: SwitchActivation.xcodeproj
        scheme: SwitchActivation
        build-settings: -resultBundlePath ui-tests
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -r results.zip ui-tests.xcresult
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
