name: GitHub

on:
  push:
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2
    - name: Close Finder Windows
      run: sudo osascript -e 'tell application "Finder" to close windows' || true
    - name: All Tests
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: SwitchActivation.xcodeproj
        scheme: SwitchActivation
        build-settings: -resultBundlePath ui-tests
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -r results.zip ui-tests.xcresult
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult
        path: results.zip
